DROP TABLE users IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  login            VARCHAR(255)            NOT NULL,
  password         VARCHAR(255)            NOT NULL,
  balance          INTEGER DEFAULT 0       NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
  ON USERS (login);

ALTER TABLE users
    ADD CONSTRAINT users_login_length_c CHECK (char_length(login) >= 2);

ALTER TABLE users
    ADD CONSTRAINT users_password_length_c CHECK (char_length(password) >= 6);